// inventory.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: inventory.proto

// กำหนด package name

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Messages สำหรับ ReserveRoom ---
type ReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	RoomTypeId    string                 `protobuf:"bytes,2,opt,name=room_type_id,json=roomTypeId,proto3" json:"room_type_id,omitempty"`
	CheckInDate   string                 `protobuf:"bytes,3,opt,name=check_in_date,json=checkInDate,proto3" json:"check_in_date,omitempty"` // รูปแบบ YYYY-MM-DD
	CheckOutDate  string                 `protobuf:"bytes,4,opt,name=check_out_date,json=checkOutDate,proto3" json:"check_out_date,omitempty"`
	RoomCount     int32                  `protobuf:"varint,5,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveRequest) Reset() {
	*x = ReserveRequest{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveRequest) ProtoMessage() {}

func (x *ReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveRequest.ProtoReflect.Descriptor instead.
func (*ReserveRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ReserveRequest) GetRoomTypeId() string {
	if x != nil {
		return x.RoomTypeId
	}
	return ""
}

func (x *ReserveRequest) GetCheckInDate() string {
	if x != nil {
		return x.CheckInDate
	}
	return ""
}

func (x *ReserveRequest) GetCheckOutDate() string {
	if x != nil {
		return x.CheckOutDate
	}
	return ""
}

func (x *ReserveRequest) GetRoomCount() int32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

type ReserveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveResponse) Reset() {
	*x = ReserveResponse{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveResponse) ProtoMessage() {}

func (x *ReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveResponse.ProtoReflect.Descriptor instead.
func (*ReserveResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReserveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// --- Messages สำหรับ CheckAvailability ---
type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomTypeId    string                 `protobuf:"bytes,1,opt,name=room_type_id,json=roomTypeId,proto3" json:"room_type_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *CheckRequest) GetRoomTypeId() string {
	if x != nil {
		return x.RoomTypeId
	}
	return ""
}

func (x *CheckRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CheckResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableRooms int32                  `protobuf:"varint,1,opt,name=available_rooms,json=availableRooms,proto3" json:"available_rooms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *CheckResponse) GetAvailableRooms() int32 {
	if x != nil {
		return x.AvailableRooms
	}
	return 0
}

// --- Messages สำหรับ ReleaseRoom ---
type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	RoomTypeId    string                 `protobuf:"bytes,2,opt,name=room_type_id,json=roomTypeId,proto3" json:"room_type_id,omitempty"`
	RoomCount     int32                  `protobuf:"varint,3,opt,name=room_count,json=roomCount,proto3" json:"room_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

func (x *ReleaseRequest) GetRoomTypeId() string {
	if x != nil {
		return x.RoomTypeId
	}
	return ""
}

func (x *ReleaseRequest) GetRoomCount() int32 {
	if x != nil {
		return x.RoomCount
	}
	return 0
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *ReleaseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\tinventory\"\xba\x01\n" +
	"\x0eReserveRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12 \n" +
	"\froom_type_id\x18\x02 \x01(\tR\n" +
	"roomTypeId\x12\"\n" +
	"\rcheck_in_date\x18\x03 \x01(\tR\vcheckInDate\x12$\n" +
	"\x0echeck_out_date\x18\x04 \x01(\tR\fcheckOutDate\x12\x1d\n" +
	"\n" +
	"room_count\x18\x05 \x01(\x05R\troomCount\"E\n" +
	"\x0fReserveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\fCheckRequest\x12 \n" +
	"\froom_type_id\x18\x01 \x01(\tR\n" +
	"roomTypeId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\"8\n" +
	"\rCheckResponse\x12'\n" +
	"\x0favailable_rooms\x18\x01 \x01(\x05R\x0eavailableRooms\"p\n" +
	"\x0eReleaseRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\x12 \n" +
	"\froom_type_id\x18\x02 \x01(\tR\n" +
	"roomTypeId\x12\x1d\n" +
	"\n" +
	"room_count\x18\x03 \x01(\x05R\troomCount\"+\n" +
	"\x0fReleaseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xe6\x01\n" +
	"\x10InventoryService\x12F\n" +
	"\x11CheckAvailability\x12\x17.inventory.CheckRequest\x1a\x18.inventory.CheckResponse\x12D\n" +
	"\vReserveRoom\x12\x19.inventory.ReserveRequest\x1a\x1a.inventory.ReserveResponse\x12D\n" +
	"\vReleaseRoom\x12\x19.inventory.ReleaseRequest\x1a\x1a.inventory.ReleaseResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inventory_proto_goTypes = []any{
	(*ReserveRequest)(nil),  // 0: inventory.ReserveRequest
	(*ReserveResponse)(nil), // 1: inventory.ReserveResponse
	(*CheckRequest)(nil),    // 2: inventory.CheckRequest
	(*CheckResponse)(nil),   // 3: inventory.CheckResponse
	(*ReleaseRequest)(nil),  // 4: inventory.ReleaseRequest
	(*ReleaseResponse)(nil), // 5: inventory.ReleaseResponse
}
var file_inventory_proto_depIdxs = []int32{
	2, // 0: inventory.InventoryService.CheckAvailability:input_type -> inventory.CheckRequest
	0, // 1: inventory.InventoryService.ReserveRoom:input_type -> inventory.ReserveRequest
	4, // 2: inventory.InventoryService.ReleaseRoom:input_type -> inventory.ReleaseRequest
	3, // 3: inventory.InventoryService.CheckAvailability:output_type -> inventory.CheckResponse
	1, // 4: inventory.InventoryService.ReserveRoom:output_type -> inventory.ReserveResponse
	5, // 5: inventory.InventoryService.ReleaseRoom:output_type -> inventory.ReleaseResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
